config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources:todo_items do
      member do
        patch :complete
      end
    end
  end
  root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  def completed?
  	!completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many:todo_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list
	before_action :set_todo_item, except: [:create]

	def create
		@todo_item = @todo_list.todo_items.create(todo_item_params)
		redirect_to @todo_list
	end

	def delete
		if @todo_item.destroy
			flash[:success] = "Todo List item was deleted."
		else
			flash[:error] = "Todo List item could not be deleted."
		end
		redirect_to @todo_list
	end

	def complete
		@todo_item.update_attribute(:completed_at, Time.now)
		redirect_to @todo_list, notice: "Todo item completed"
	end

	private

	def set_todo_list
		@todo_list = TodoList.find(params[:todo_list_id])
	end

	def set_todo_item
		@todo_item = @todo_list.todo_items.find(params[:id])
	end

	def todo_item_params
		params[:todo_item].permit(:content)
	end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build],:html=>{:style=>'width:66vw;display:flex;flex-direction:column;justify-content:space-between;align-items:center	'})  do |f| %>
	<%= f.text_field :content, placeholder: "Add New Todo",class:'p-2 m-2 w-2/3 outline-none border-b-2 border-bg-gray-300 transition duration-700  border-teal-400 ' %>
	<%= f.submit class:'w-1/5 m-2 cursor-pointer text-white bg-blue-800 p-4 rounded-full transition duration-500 hover:-translate-y-1 ' %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="flex flex-col h-full justify-center items-center w-full">
	<% if todo_item.completed? %>
		
		<div class="flex w-full items-center">
			<p  class="w-2/3 line-through  text-gray-800 p-2 border border-[#900C3F] hover:bg-[#900C3F] hover:text-white transition duration-500 rounded-lg"><b><%= todo_item.content %></b></p>
			<div class="flex justify-around">
			<button class="transition duration-500 flex-no-shrink p-2 mr-2 border-2 rounded hover:text-white text-green-500 border-green-500 hover:bg-green-500">Completed</button>
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
				<button class="transition duration-500 flex-no-shrink p-2  border-2 rounded text-red-500 border-red-500 hover:text-white hover:bg-red-500">Remove</button>
			<% end %>
			</div>
		</div>
	<% else %>
			<div class="flex w-full  items-center justify-between p-2">
				<p class="w-2/3 text-green-600 p-2 border border-[#900C3F] rounded-lg"><b><%= todo_item.content %></b></p>
				<div class="flex justify-between	w-1/4">
				<button class="transition duration-500 flex-no-shrink p-2 mr-2 border-2 rounded hover:text-white text-blue-500 border-blue-500 hover:bg-blue-500">Not Completed</button>
				<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
					<button class="transition duration-500 flex-no-shrink p-2  border-2 rounded text-red-500 border-red-500 hover:text-white hover:bg-red-500">Remove</button>
				<% end %>
				</div>
			</div>
		
	<% end %>
</div>

app/views/todo_lists/_form.html.erb
<div class="w-full h-full">

<%= form_for(@todo_list,:html=>{:style=>'height:100%'}) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="border-2 shadow-lg p-2 h-full w-full border-white flex flex-col justify-around items-center">
      <div class="flex items-center justify-around  w-3/4">
        <%= f.label :title,class:'w-1/3 text-center ' %><br>
        <%= f.text_field :title,class:'p-2 w-2/3 outline-none border-b-2 border-bg-gray-300 transition duration-700 border-teal-400 '  %>
      </div>
      <div class="flex items-center justify-around h-full w-3/4">
        <%= f.label :description,class:'w-1/3 text-center' %><br>
        <%= f.text_area :description,class:'p-2 w-2/3  resize-none h-1/2 outline-none border-2 border-bg-gray-300 transition duration-700 border-teal-400 '  %>
      </div>
      <div class="w-3/4 flex justify-center ">
        <%= f.submit class:'w-1/5 cursor-pointer text-white bg-blue-800 p-4 rounded-full transition duration-500 hover:-translate-y-1' %>
      </div>
  </div>
<% end %>

</div>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">
  <p>
    <strong>Title:</strong>
    <%= todo_list.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= todo_list.description %>
  </p>

</div>

app/views/todo_lists/edit.html.erb
<div class="flex flex-col justify-center items-center w-full h-screen">
<h1 class="text-xl font-bold">Edit Todo List</h1>

<div class="w-3/4 mt-2 flex h-2/3 justify-center items-center">
	<%= render 'form' %>
</div>

<div class=" m-2">
	<%= link_to 'Cancel', todo_lists_path,class:'text-blue-500' %>
</div>

</div>

app/views/todo_lists/index.html.erb
<div class="flex flex-col h-screen w-full justify-center items-center ">
    <div class=" w-full h-5/6 flex flex-col items-center">
        <h1 class="text-gray-700 text-xl font-bold">Todo List Application</h1>

        <div class="m-2 p-2 w-32 border-2 text-white text-center bg-[#900C3F] rounded-full hover:bg-[#A40F48]">
            <%= link_to "Add Todo List", new_todo_list_path %>
        </div>
        <div class="w-1/2 cursor-pointer h-2/3 flex justify-center" >
          <% @todo_lists.each do |todo_list| %>
             <%= link_to todo_list do %>
                <div class="transition duration-500 flex flex-col mb-2 items-center rounded-lg hover:shadow-lg justify-center w-3/4 m-2 border-2 border-teal-300 h-1/3">
                    <p class="text-xl font-bold"><%= link_to todo_list.title, todo_list %></p>
                    <p class="text-gray-400 font-semibold"><%= todo_list.description %></p>               
                </div>
             <% end %> 
          <% end %> 
        </div>
    </div>
</div>

app/views/todo_lists/new.html.erb
<div class="flex flex-col justify-center items-center w-full h-screen">

<h1 class="text-xl font-bold ">New todo list</h1>

<div class="w-3/4  flex h-2/3 justify-center items-center">
<%= render "form", todo_list: @todo_list %>
</div>

<br>

<div>
  <%= link_to "Back to todo lists", todo_lists_path,class:'text-blue-500' %>
</div>

</div>

app/views/todo_lists/show.html.erb
<div class="flex flex-col justify-center items-center w-full min-h-screen ">

	<div class="flex flex-col justify-center items-center w-3/4 h-5/6 max-h-screen border-2 rounded-lg shadow-lg">
				<div class="flex flex-col items-center justify-center h-1/6">
						<h2 class="text-xl font-bold"><%= @todo_list.title %></h2>
						<p class="  text-gray-400 font-semibold"><%= @todo_list.description %></p>
				</div>

				<div class="flex flex-col justify-center items-center h-5/6 w-full 	">
					<div class="flex flex-col justify-center items-center w-full h-2/3 overflow-y-scroll p-2">
					<%= render @todo_list.todo_items %>
					</div>
					<div class="w-full h-1/3 mb-2">
						<%= render "todo_items/form" %>
					</div>
				</div>	
	</div>
	<div class="w-1/3 m-2 flex justify-around">
				<%= link_to 'Edit', edit_todo_list_path(@todo_list),class:"border-blue-800 border-2 px-4 transition duration-500 rounded-lg text-blue-800 hover:bg-blue-800 hover:text-white" %> 
				<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" },class:"border-red-800 border-2 px-4 transition duration-500 rounded-lg text-red-800 hover:bg-red-800 hover:text-white"
			%> 
			<%= link_to 'Back', todo_lists_path,class:"border-green-800 border-2 px-4 transition duration-500 rounded-lg text-green-800 hover:bg-green-800 hover:text-white" %>
	</div>

</div>